FROM python:3.11 AS builder

WORKDIR /usr/src/app

RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

RUN pip install --upgrade pip

COPY . .
RUN pip install --no-cache-dir -r requirements-scanner.txt

FROM python:3.11 AS scanner
WORKDIR /usr/src/app
ENV PATH=/venv/bin:$PATH
ENV TIME=5
COPY --from=builder /venv /venv
COPY --from=builder /usr/src/app/src/scanner-mock/main.py .

CMD exec python3 main.py --outpath /inbox --time ${TIME:-5}
