# coding: utf-8

"""
    PDF Classifier API

    REST API to classify PDF files using a smart backend

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
from sys import prefix

from fastapi import FastAPI

from openapi_server.apis.classification_api import router as ClassificationApiRouter

app = FastAPI(
    title="PDF Classifier API",
    description="REST API to classify PDF files using a smart backend",
    version="1.0.0",
)

app.include_router(ClassificationApiRouter, prefix="/api/v1")
