name: Deploy Package to GHCR

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GHCR

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image with release tags
      if: github.event_name == 'release'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{github.repository_name}}:${{ github.sha }} 
          ghcr.io/${{ github.repository_owner }}/${{github.repository_name}}:${{ github.ref_name }} 
          ghcr.io/${{ github.repository_owner }}/${{github.repository_name}}:latest

    - name: Build and push Docker image for main branch
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{github.repository_name}}:${{ github.sha }} 
          ghcr.io/${{ github.repository_owner }}/${{github.repository_name}}:main          
