name: Deploy Package to GHCR

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GHCR

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU for multiplatform build
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image for service with release tags
      if: github.event_name == 'release'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }} 
          ghcr.io/${{ github.repository }}:${{ github.ref_name }} 
          ghcr.io/${{ github.repository }}:latest

    - name: Build and push Docker image for scanner-mock with release tags
      if: github.event_name == 'release'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.scanner
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/${{ github.repository }}-scanner-mock:${{ github.sha }} 
          ghcr.io/${{ github.repository }}-scanner-mock:${{ github.ref_name }} 
          ghcr.io/${{ github.repository }}-scanner-mock:latest

    - name: Build and push Docker image for service main branch (only arm64)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/arm64
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }} 
          ghcr.io/${{ github.repository }}:main          

    - name: Build and push Docker image for scanner-mock main branch (only arm64)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        file: Dockerfile.scanner
        platforms: linux/arm64
        tags: |
          ghcr.io/${{ github.repository }}-scanner-mock:${{ github.sha }} 
          ghcr.io/${{ github.repository }}-scanner-mock:main          
